id: P008161
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG18562
  title: སྙིགས་དུས་འགྲོ་བ་ཡོངས་ཀྱི་སྐྱབས་མགོན་ཞབས་དཀར་རྡོ་རྗེ་འཆང་ཆེན་པོའི་རྣམ་པར་ཐར་པ་རྒྱས་པར་བཤད་པ།
  author: ''
  volumes:
    2d95e17b904f4d90b9bc1624ab510438:
      image_group_id: I1KG18596
      title: ''
      volume_number: 1
      total_pages: 616
    e43dff275e8c4f37a8df3be34528e6f5:
      image_group_id: I1KG18597
      title: ''
      volume_number: 2
      total_pages: 596
ebook_metadata:
  title: སྙིགས་དུས་འགྲོ་བ་ཡོངས་ཀྱི་སྐྱབས་མགོན་ཞབས་དཀར་རྡོ་རྗེ་འཆང་ཆེན་པོའི་རྣམ་པར་ཐར་པ་རྒྱས་པར་བཤད་པ།
  author: ''
  sku: P008161
  cover: cover.jpg
  layers:
  - pagination
