id: opecha:P008161
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG18562
  title: སྙིགས་དུས་འགྲོ་བ་ཡོངས་ཀྱི་སྐྱབས་མགོན་ཞབས་དཀར་རྡོ་རྗེ་འཆང་ཆེན་པོའི་རྣམ་པར་ཐར་པ་རྒྱས་པར་བཤད་པ།
  volume: ''
  author: ''
